# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
name: secondPipeline
trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: secondPipeline
      source: cvakumark.DotNetAzureDevOps
      project: DotNetAzureDevOps
      trigger: true
stages:
- stage: checkout
  jobs:
    - job: checkout
      steps:
      - checkout: self
      - script: ls $(Build.SourcesDirectory)
      - script: echo Triggered by the source pipeline

      
- stage: Build
  jobs:
    - job: 'Maven_Build'
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: "JaCoCo"
            summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
            reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
            failIfCoverageEmpty: true
- stage: Deployment
  jobs:
  - deployment: 
    displayName: Dev Deploy
    environment: Dev_Maven
    strategy:
     runOnce:
      deploy:
       steps:
       - script: echo Running in the Dev-Maven environment as deployment job
         displayName: 'Dev Maven based stage'
